<!DOCTYPE html>
<html>
<head>
<title><%=htm_title%></title>
<link href="/kpi/css/css.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="/kpi/css/jquery-confirm.css"/>
<link rel="stylesheet" href="/kpi/css/bundled.css"/>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1">
<script language="javascript" src="/kpi/script/CoCalendar.js" TYPE="text/javascript"></script>
<!--script language="javascript" src="script/ExpertGrid4_Include.js"></script //-->
</head>
<script language=javascript src="/kpi/module/common.js"></script>
<!--script language="JavaScript" src="/kpi/script/AIScriptCS.js"></script -->

<script language="javascript" src="/kpi/ibsheet7/ibleaders.js?version=20220331"></script>
<script language="javascript" src="/kpi/ibsheet7/ibsheet.js"></script>
<script language="javascript" src="/kpi/ibsheet7/ibsheetinfo.js"></script>
<script language="javascript" src="/kpi/script/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/kpi/ibsheet7/highcharts/highcharts.js"></script>
<script type="text/javascript" src="/kpi/ibsheet7/highcharts/highcharts-more.js"></script>
<script type="text/javascript" src="/kpi/ibsheet7/highcharts/modules/boost.js"></script>
<script language="javascript" src="/kpi/ibsheet7/ibchart.js"></script>
<script language="javascript" src="/kpi/ibsheet7/ibchartinfo.js"></script>

<script src="/kpi/script/jquery-confirm.js"></script>
