
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<form name="frm" method="post" action="<%=actionname%>">
<!------------제목타이틀소메뉴시작--------->
<table width="100%" border="0" cellspacing="0" cellpadding="0">  
  <tr>
    <td width="100%" height="38" style="border-bottom:1px solid #cccccc;" /*background="/kpi/img/pop_tbg01.gif"*/>
      <table border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <!--<td width="5"><img src="/kpi/img/pop_img02.gif" width="5" height="38"></td>-->
          <td width="30"> 
            <div align="center"><img src="/kpi/img/pop_point01.gif" width="8" height="17"></div></td>
          <td class="pop_title02"><%=htm_title%></td>
        </tr>
      </table>
    </td>
  </tr>
<!----------제목타이틀소메뉴끝---------->
  <tr><td>&nbsp;</td></tr> 
  <tr> 
    <td align="center" valign="top" class="pdLR">      