<!DOCTYPE html>
<html>
<head>
<title><%=htm_title%></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1">
<link rel="stylesheet" href="/kpi/css/common.css" type="text/css">
<link rel="stylesheet" href="/kpi/css/css.css" type="text/css">
<link rel="stylesheet" href="/kpi/css/jquery-confirm.css"/>
<link rel="stylesheet" href="/kpi/css/bundled.css"/>

</head>
<script language=javascript src="/kpi/module/common.js"></script>
<script language="javascript" src="/kpi/script/CoCalendar.js"></script>

<script language="javascript" src="/kpi/ibsheet7/ibleaders.js?version=20211201"></script>
<script language="javascript" src="/kpi/ibsheet7/ibsheet.js"></script>
<script language="javascript" src="/kpi/ibsheet7/ibsheetinfo.js"></script>
<script language="javascript" src="/kpi/script/jquery-1.7.2.min.js"></script>
<script src="/kpi/script/jquery-confirm.js"></script>